version: '3.8' # Версия синтаксиса Docker Compose

services:
  api:
    build: . # Docker будет искать Dockerfile в текущей директории
    ports:
      - "8000:8000" # Маппинг портов: HOST_PORT:CONTAINER_PORT
    env_file:
      - .env # Загрузка переменных окружения из файла .env в контейнер.
              # Это ПРАВИЛЬНЫЙ способ передачи чувствительных данных в контейнер.
    volumes:
      # Этот том монтирует директорию на хосте для сохранения данных SQLite.
      # Без этого, notes.db будет создаваться внутри контейнера и исчезать при его удалении.
      # Если вы используете внешнюю БД (PostgreSQL, MySQL), этот том не нужен.
      - notes_data:/app/notes.db

    # Если вы хотите отлаживать с --reload (только для разработки!):
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # volumes:
    #   - .:/app # Для --reload нужен том, чтобы код на хосте был виден в контейнере

volumes:
  notes_data: # Объявление именованного тома для хранения данных SQLite